#pragma once

#define SRC_WIDTH 1024
#define SRC_HEIGHT 1024
#define WINDOW_TITLE "QEngine"


#define GLOBAL_UNIFORM_CAMERA_MATRIES_INDEX 0
#define GLOBAL_UNIFORM_CAMERA_MATRIES_SIZE 144


#define UNIFORM_USE_DIFFUSE_MAP "useDiffuseMap"
#define UNIFORM_DIFFUSE_MAP "diffuseMap"
#define UNIFORM_DIFFUSE_MAP_CODE 0

#define UNIFORM_USE_SPECULAR_MAP "useSpecularMap"
#define UNIFORM_SPECULAR_MAP "specularMap"
#define UNIFORM_SPECULAR_MAP_CODE 1

#define UNIFORM_USE_NORMAL_MAP "useNormalMap"
#define UNIFORM_NORMAL_MAP "normalMap"
#define UNIFORM_NORMAL_MAP_CODE 2

