#pragma once

#define SRC_WIDTH 1024
#define SRC_HEIGHT 1024
#define WINDOW_TITLE "QEngine"

//	Camera Params
#define CAMERA_NEAR 0.1f
#define CAMERA_FAR 1000.0f
#define CAMERA_ZOOM 45.0f
#define MAIN_CAMERA_MOVE_SPEED 12.5f

//	Direction Light Shadow
#define SHADOWMAP_EYE_DISTANCE 150.0f
#define SHADOWMAP_CSM_SHADOW_DISTANCE 150
#define SHADOWMAP_OUTER_WIDTH 20.0
#define SHADOWMAP_CASACADE_COUNT 4
#define SHADOWMAP_DEFAULT_SIZE 1024
#define SHADOWMAP_CASCADE_SPLITS_0 0.01f
#define SHADOWMAP_CASCADE_SPLITS_1 0.11f
#define SHADOWMAP_CASCADE_SPLITS_2 0.4f
#define SHADOWMAP_CASCADE_SPLITS_3 1.0f
#define SHADOWMAP_POINT_LIGHT_NEAR 0.1f
#define SHADOWMAP_POINT_LIGHT_FAR  100.0f


#define GLOBAL_UNIFORM_CAMERA_MATRIES_INDEX 0
#define GLOBAL_UNIFORM_CAMERA_MATRIES_SIZE 144


#define UNIFORM_USE_DIFFUSE_MAP "useDiffuseMap"
#define UNIFORM_DIFFUSE_MAP "diffuseMap"
#define UNIFORM_DIFFUSE_MAP_CODE 0

#define UNIFORM_USE_SPECULAR_MAP "useSpecularMap"
#define UNIFORM_SPECULAR_MAP "specularMap"
#define UNIFORM_SPECULAR_MAP_CODE 1

#define UNIFORM_USE_NORMAL_MAP "useNormalMap"
#define UNIFORM_NORMAL_MAP "normalMap"
#define UNIFORM_NORMAL_MAP_CODE 2

